exceptions = ['cherkasy.ua', 'qc.com', 'no.com', 'hu.com', 'uy.com', 'za.bz',
'gb.com', 'ar.com', 'se.com', 'ivano-frankivsk.ua', 'kr.com', 'kharkiv.ua',
'com.se']

domains_list = ['cafe', 'business', 'email', 'repair', 'love', 'care',
'in.net', 'in.ua', 'uk.com', 'reisen', 'zhitomir.ua', 'expert', 'red',
'tv', 'solutions', 'sarl', 'cn.com', 'house', 'online', 'farm', 'top',
'gift', 'capital', 'co.ua', 'careers', 'dating', 'ua', 'fund', 'cherkasy.ua',
'memorial', 'computer', 'gripe', 'bingo', 'cruises', 'coupons', 'industries',
'fyi', 'org', 'co.com', 'la', 'engineering', 'kim', 'juegos', 'chernivtsi.ua',
'zone', 'enterprises', 'supplies', 'city', 'lg.ua', 'parts', 'guru', 'voyage',
'gifts', 'boutique', 'kiev.ua', 'catering', 'ck.ua', 'life', 'codes', 'works',
'creditcard', 'pro', 'qc.com', 'photography', 'golf', 'dp.ua', 'rivne.ua',
'cv.ua', 'villas', 'guitars', 'education', 'bar', 'space', 'if.ua',
'cherkassy.ua', 'fitness', 'no.com', 'volyn.ua', 'jpn.com', 'lviv.ua',
'eu.com', 'diamonds', 'wtf', 'town', 'tires', 'condos', 'bike', 'construction',
'pink', 'lighting', 'world', 'exposed', 'singles', 'directory', 'cheap', 'maison',
'biz', 'deals', 'kharkov.ua', 'cab', 'watch', 'tech', 'media', 'legal', 'finance',
'tattoo', 'net', 'schule', 'foundation', 'sumy.ua', 'te.ua', 'hu.com', 'delivery',
'donetsk.ua', 'coffee', 'info', 'loans', 'kherson.ua', 'od.ua', 'training', 'pictures',
'rovno.ua', 'photo', 'kitchen', 'com', 'apartments', 'land', 'christmas', 'uy.com',
'team', 'partners', 'systems', 'florist', 'cool', 'ternopil.ua', 'graphics', 'se.net',
'plus', 'de.com', 'lt.ua', 'furniture', 'academy', 'poltava.ua', 'odessa.ua', 'name',
'hiphop', 'fans', 'br.com', 'jp.net', 'company', 'black', 'vn.ua', 'limo', 'sm.ua',
'flowers', 'associates', 'clothing', 'lugansk.ua', 'blue', 'investments', 'za.bz',
'hosting', 'center', 'gratis', 'ventures', 'discount', 'ae.org', 'cards', 'camp',
'digital', 'credit', 'marketing', 'exchange', 'website', 'uzhgorod.ua', 'place',
'claims', 'rv.ua', 'su', 'gb.com', 'limited', 'tax', 'gold', 'africa.com', 'km.ua',
'press', 'ar.com', 'chat', 'cleaning', 'se.com', 'surgery', 'click', 'yalta.ua',
'hockey', 'vacations', 'hu.net', 'holiday', 'jewelry', 'glass', 'kr.ua', 'properties',
'zp.ua', 'guide', 'holdings', 'pl.ua', 'domains', 'coach', 'site', 'host', 'recipes',
'ivano-frankivsk.ua', 'church', 'football', 'dog', 'college', 'express', 'toys', 'cn.ua',
'clinic', 'community', 'flights', 'cc', 'show', 'gr.com', 'crimea.ua', 'immo',
'plumbing', 'green', 'rentals', 'productions', 'gallery', 'zaporizhzhe.ua', 'shoes',
'chernovtsy.ua', 'technology', 'gb.net', 'services', 'za.com', 'kr.com', 'builders',
'money', 'xyz', 'accountants', 'management', 'kharkiv.ua', 'biz.ua', 'us.com', 'audio',
'help', 'club', 'support', 'sexy', 'ru.com', 'org.ua', 'tienda', 'financial', 'report',
'tours', 'khmelnitskiy.ua', 'bargains', 'healthcare', 'cash', 'property', 'mex.com',
'tips', 'tools', 'us.org', 'today', 'uz.ua', 'pics', 'solar', 'укр', 'lease', 'fail',
'institute', 'uk.net', 'shiksha', 'ks.ua', 'viajes', 'ink', 'lol', 'kirovograd.ua',
'style', 'estate', 'com.ua', 'com.de', 'photos', 'dn.ua', 'events', 'net.ua', 'diet',
'international', 'vision', 'zt.ua', 'sebastopol.ua', 'camera', 'lutsk.ua', 'restaurant',
'design', 'sa.com', 'kh.ua', 'equipment', 'pizza', 'vinnica.ua', 'rent', 'university',
'agency', 'lgbt', 'blackfriday', 'contractors', 'com.se', 'dental', 'fish', 'school',
'tennis', 'link', 'network', 'direct', 'pw', 'energy', 'ru', 'casino', 'rest', 'supply',
'kyiv.ua', 'insure']
